Allowed for different path settings between OSX/Linux that is written out during install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -3,7 +3,7 @@ DOTFILES=~/dotfiles
 PACMAN="zsh git"
 AUR="vim-solarized-git dircolors-solarized-git"
 MACPORT="zsh git-core"
-LINUX=false
+LINUX="false"
 
 if `which sudo > /dev/null 2>&1`; then
 	sudo=sudo
@@ -21,7 +21,7 @@ rc=$?
 # Check if running Arch Linux
 echo "Verifying required packages are installed..."
 if grep -vq "Arch Linux" /etc/os-release > /dev/null 2>&1; then
-	LINUX=true
+	LINUX="true"
 
 	# Check that aura is installed/up-to-date
 	INST_AURA=`pacman -Q aura 2>&1|grep -oE '[0-9]\.[0-9.]+(\-[0-9])?'`
@@ -84,7 +84,7 @@ elif uname -a|grep -qi darwin > /dev/null 2>&1; then
 		port installed|grep $package > /dev/null 2>&1 || MPINST="$MPINST $package"
 	done
 	[[ $MPINST == "" ]] || sudo port install $MPINST
-	cp $DOTFILES/install-files/mac-gitconfig ~/.gitconfig
+	cp $DOTFILES/install-files/mac/.* ~
 	echo "Since you are running OS X. Please ensure 'AcceptEnv' in /etc/sshd_config includes 'IHAVEPATCHEDFONTS'"
 	echo "Also check that 'Defaults env_keep += \"SSH_TTY\"' and 'Defaults env_keep += \"IHAVEPATCHEDFONTS\"' are in sudoers"
 else
@@ -94,13 +94,27 @@ else
 fi
 
 if [ "$LINUX" == "true" ]; then
-	cp $DOTFILES/install-files/arch-gitconfig ~/.gitconfig
+	echo -n "Copying linux specific files... "
+	cp $DOTFILES/install-files/linux/.* ~
+	rc=$?
+	[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+	[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]"
+
 	echo -n "Copying fonts... "
 	$sudo mkdir -p /usr/share/fonts/OTF
 	$sudo cp $DOTFILES/install-files/fonts/OTF/* /usr/share/fonts/OTF/
 	rc=$?
 	[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
 	[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]"
+
+	echo -n "Setting PATH... "
+	echo "export PATH=$PATH:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/bin/core_perl" >> ~/.zshrc
+	rc=$?
+	[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+	[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e[00m]"
+else
+	# Presumably OS X
+	echo "export PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/X11/bin" >> ~/.zshrc
 fi
 
 echo -n "Installing/updating oh-my-zsh... "
