Added confirmation of steps and cleaned up SSHD/sudoers config messages

diff --git a/install b/install
--- a/install
+++ b/install
@@ -5,8 +5,12 @@ AUR="vim-solarized-git dircolors-solarized-git"
 MACPORT="zsh git-core"
 LINUX=false
 
-echo "Copying dotfiles..."
+echo -n "Copying dotfiles... "
 rsync -a --exclude=install --exclude=install-files --exclude=.git $DOTFILES/.* ~/
+rc=$?
+[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e00m]"
+
 # Check if running Arch Linux
 echo "Verifying required packages are installed..."
 if grep -vq "Arch Linux" /etc/os-release > /dev/null 2>&1; then
@@ -33,28 +37,30 @@ if grep -vq "Arch Linux" /etc/os-release > /dev/null 2>&1; then
 	[[ $PACINST == "" ]] || sudo pacman -S $PACINST
 	[[ $AURINST == "" ]] || sudo aura -A $AURINST
 
-# Check for patched fonts config in sshd
+	# Check for patched fonts config in sshd
+	echo -n "Checking SSHD config... "
 	if `grep -q "AcceptEnv.*IHAVEPATCHEDFONTS" /etc/ssh/sshd_config`; then
-		echo "SSHD already configured correctly"
+		echo -e "[ \e[1;32mOK\e[00m ]"
 	else
-		echo "SSHD does not appear to be configured correctly"
+		echo -e "[\e[1;33mFixing\e[00m]"
 		if `grep -q "AcceptEnv" /etc/ssh/sshd_config`; then
-			echo "AcceptEnv exists in SSHD config but is not correct; adding IHAVEPATCHEDFONTS..."
 			sudo sed -i '/^AcceptEnv/ s/$/ IHAVEPATCHEDFONTS/' /etc/ssh/sshd_config
 		else
-			echo "AcceptEnv does not exist in SSHD config, Adding it with IHAVEPATCHEDFONTS"
 			echo "AcceptEnv IHAVEPATCHEDFONTS" | sudo tee -a /etc/ssh/sshd_config > /dev/null
 		fi
-		echo "Restarting SSHD..."
+		echo -n "Restarting SSHD... "
 		sudo systemctl restart sshd
+		rc=$?
+		[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+		[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e00m]"
 	fi
 
-# Check for SSH_TTY config in sudoers
+	# Check for SSH_TTY config in sudoers
+	echo -n "Checking sudoers config... "
 	if `sudo grep -q "^Defaults.*env_keep.*SSH_TTY" /etc/sudoers`; then
-		echo "Sudoers already configured"
+		echo -e "[ \e[1;32mOK\e[00m ]"
 	else
-		echo "Sudoers doesnot appear to be configured correctly."
-		echo 'Adding Defaults env_keep += "SSH_TTY"'
+		echo -e "[\e[1;33mFixing\e[00m]"
 		echo -e 'Defaults\tenv_keep += "SSH_TTY"' | sudo tee -a /etc/sudoers > /dev/null
 	fi
 	
@@ -75,18 +81,23 @@ fi
 
 if [ "$LINUX" == "true" ]; then
 	cp $DOTFILES/install-files/arch-gitconfig ~/.gitconfig
-	echo "Copying fonts..."
+	echo -n "Copying fonts... "
 	sudo cp $DOTFILES/install-files/fonts/OTF/* /usr/share/fonts/OTF/
+	rc=$?
+	[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+	[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e00m]"
 fi
 
-echo "Installing/updating oh-my-zsh..."
+echo -n "Installing/updating oh-my-zsh... "
 rm -rf ~/.oh-my-zsh
 cd ~
 tar zxf $DOTFILES/install-files/oh-my-zsh.tar.gz
 cd ~/.oh-my-zsh
 git reset --hard origin/master > /dev/null 2>&1
 git pull > /dev/null 2>&1
-rm -rf ~/.git
+rc=$?
+[[ $rc == 0 ]] && echo -e "[ \e[1;32mOK\e[00m ]"
+[[ $rc != 0 ]] && echo -e "[\e[1;31mFAILED\e00m]"
 
 echo "Changing shell to ZSH..."
 echo $SHELL|grep -q zsh || chsh -s `which zsh`
