Update bootstrap script and include fedora packages

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -34,28 +34,15 @@ if [[ ! -d $DOTFILES ]]; then
     exit 1
 fi
 
-ok() {
-    echo=echo
-    if [[ $RELEASE == "Mac" ]]; then
-        if ! which gecho &>/dev/null; then
-            echo " [ OK ]"
-            return
-        else
-            echo=gecho
-        fi
-    fi
-    $echo -e " [ \e[1;32mOK\e[00m ]"
-}
-
 git_update() {
     repo="$1"
     dest="$2"
     if [[ -d "$dest" ]]; then
         cd "$dest"
-        git reset --hard origin/master >/dev/null 2>&1
-        git pull >/dev/null 2>&1
+        git reset --hard origin/master
+        git pull
     else
-        git clone "$repo" "$dest" >/dev/null 2>&1
+        git clone "$repo" "$dest"
     fi
 }
 
@@ -68,8 +55,8 @@ file_download() {
     fi
 }
 
-
 install_packages_meta() {
+    echo
     echo "Verifying required packages are installed."
     case $RELEASE in
     'Debian' | 'Ubuntu' | 'Raspbian') install_command=install_packages_debian ;;
@@ -77,6 +64,7 @@ install_packages_meta() {
     'Mac') install_command=install_packages_mac ;;
     'Gentoo') install_command=install_packages_gentoo ;;
     'Arch') install_command=install_packages_arch ;;
+    'Fedora') install_command=install_packages_fedora ;;
     *)
         cat <<-EOF
 			You are not using a supported distro; package installation will be skipped. Make sure the required packages have been installed.
@@ -96,6 +84,7 @@ create_package_list() {
 }
 
 install_aws_cli() {
+    echo
     echo "Installing AWS CLI..."
 
     if ! which aws &>/dev/null; then
@@ -119,20 +108,20 @@ install_aws_cli() {
             ;;
         esac
     fi
-    ok
 }
 
 install_packages_al2() {
     echo "OS appears to be Amazon Linux 2..."
 
-    echo -n "Installing required packages..."
+    echo "Installing required packages..."
     create_package_list al2
+    # shellcheck disable=SC2086
     sudo yum install -y $PACINST
     install_package_groups_al2
 }
 
 install_package_groups_al2() {
-    echo -n "Installing required package groups..."
+    echo "Installing required package groups..."
     create_package_list al2-groups
     IFS=$'\n' command eval 'for group in $PACINST; do sudo yum groupinstall -y $group; done'
 }
@@ -140,17 +129,19 @@ install_package_groups_al2() {
 install_packages_gentoo() {
     echo "OS appears to be Gentoo..."
 
-    echo -n "Installing required packages..."
+    echo "Installing required packages..."
     create_package_list gentoo
 
     # This is faster than using --noreplace which needs to compute dependencies
     FILTERED_PACINST=""
     for package in $PACINST; do
+        # shellcheck disable=SC2086
         if ! qlist -Iv $package >/dev/null; then
             FILTERED_PACINST+="$package"
         fi
     done
     if [[ $FILTERED_PACINST ]]; then
+        # shellcheck disable=SC2086
         sudo emerge $FILTERED_PACINST
     fi
 }
@@ -158,11 +149,20 @@ install_packages_gentoo() {
 install_packages_debian() {
     echo "OS appears to be Debian/Ubuntu..."
 
-    echo -n "Installing required packages..."
+    echo "Installing required packages..."
     create_package_list debian
     sudo apt-get update
-    sudo apt-get install -y $PACINST &>/dev/null
-    ok
+    # shellcheck disable=SC2086
+    sudo apt-get install -y $PACINST
+}
+
+install_packages_fedora() {
+    echo "OS appears to be Fedora..."
+    create_package_list fedora
+
+    echo "Installing required packages..."
+    # shellcheck disable=SC2086
+    sudo rpm-ostree install -y --idempotent $PACINST
 }
 
 install_packages_arch() {
@@ -176,15 +176,14 @@ install_packages_arch() {
             git clone https://aur.archlinux.org/yay.git
             cd yay
             makepkg -si --noconfirm
-            yay --save --makepkg $HOME/.local/bin/customize-makepkg
+            yay --save --makepkg "$HOME"/.local/bin/customize-makepkg
         )
     fi
 
-    pyenv shell system &>/dev/null || :
-    echo -n "Installing required packages..."
+    echo "Installing required packages..."
     create_package_list arch
-    yay -S --noconfirm --needed $PACINST &>/dev/null
-    ok
+    # shellcheck disable=SC2086
+    yay -S --noconfirm --needed $PACINST
 
     sudo systemctl enable --now cronie
 }
@@ -217,17 +216,19 @@ update_submodules() {
 }
 
 update_scripts() {
+    echo
     echo "Updating scripts..."
     git_update "https://github.com/justin8/scripts.git" "$HOME/.scripts"
 }
 
 install_fzf() {
-    echo -n "Installing fzf..."
-    "$DOTFILES/fzf/install" --all &>/dev/null
-    ok
+    echo
+    echo "Installing fzf..."
+    "$DOTFILES/fzf/install" --all
 }
 
 install_mise() {
+    echo
     echo -n "Installing mise..."
     if [[ ! -e $HOME/.local/bin/mise ]]; then
         curl https://mise.run | sh
@@ -236,15 +237,16 @@ install_mise() {
     fi
 }
 
-
 install_python_dev_dependencies() {
-    ~/.local/bin/mise activate bash
+    eval "$(~/.local/bin/mise activate bash)"
 
     if ! which ipython &>/dev/null; then
+        echo
         echo "Installing iPython... "
         pip install --user ipython
     fi
     if ! which poetry &>/dev/null; then
+        echo
         echo "Installing poetry... "
         pip install --user poetry
         # Configure poetry while we're at it
@@ -254,17 +256,21 @@ install_python_dev_dependencies() {
 }
 
 install_fonts() {
-    echo -n "Installing Meslo Nerd Fonts..."
+    echo
+    echo "Installing Meslo Nerd Fonts..."
     FONT_DIR="$HOME/.local/share/fonts/"
     [[ $RELEASE == Mac ]] && FONT_DIR="$HOME/Library/Fonts/"
+    FONT_FILE="$FONT_DIR/Meslo LG S Regular Nerd Font Complete.ttf"
 
-    file_download "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip" "$DOTFILES/Meslo.zip"
-    unzip -nd "$FONT_DIR" "$DOTFILES/Meslo.zip" &>/dev/null
-    ok
+    if ! [[ -f "$FONT_FILE" ]]; then
+        file_download "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Meslo.zip" "$DOTFILES/Meslo.zip"
+        unzip -nd "$FONT_DIR" "$DOTFILES/Meslo.zip"
+    fi
 }
 
 configure_gitconfig() {
-    echo -n "Configuring gitconfig..."
+    echo
+    echo "Configuring gitconfig..."
     git config --global push.default current
     git config --global color.ui auto
     git config --global merge.conflictstyle diff3
@@ -281,7 +287,6 @@ configure_gitconfig() {
     # Brazil CLI recommendations
     git config --global core.pager "less -FMRiX"
     git config --global alias.dag "log --graph --format='format:%C(yellow)%h%C(reset) %C(blue)"%an" <%ae>%C(reset) %C(magenta)%cr%C(reset)%C(auto)%d%C(reset)%n%s' --date-order"
-    ok
 }
 
 configure_vim() {
@@ -292,7 +297,8 @@ configure_vim() {
 }
 
 install_vimplug() {
-    echo -n "Installing/updating vimplug..."
+    echo
+    echo "Installing/updating vimplug..."
     if [[ -f ~/.vim/autoload/plug.vim ]]; then
         # Vim always seems to have a return of 1...
         vim -esu ~/.vimrc +PlugUpgrade +qa || true
@@ -301,21 +307,21 @@ install_vimplug() {
         curl -sSfLo ~/.vim/autoload/plug.vim \
             https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
     fi
-    ok
 }
 
 install_vim_plugins() {
-    echo -n "Installing vim plugins..."
+    echo
+    echo "Installing/updating vim plugins..."
     # Vim always seems to have a return of 1...
     vim -esu ~/.vimrc +PlugClean! +PlugUpdate +qa || true
-    ok
 }
 
 install_vim_plugin_dependencies() {
-    echo -n "Installing dependencies for vim plugins..."
+    echo
+    echo "Installing dependencies for vim plugins..."
+    eval "$(~/.local/bin/mise activate bash)"
     pip install python-lsp-server python-lsp-black python-lsp-isort pylsp-mypy
     npm i -g bash-language-server typescript-language-server typescript
-    ok
 }
 
 configure_oh_my_zsh() {
@@ -325,7 +331,8 @@ configure_oh_my_zsh() {
 change_shell() {
     local setshell=0
     local newshell=zsh
-    echo -n "Changing shell to $newshell..."
+    echo
+    echo "Setting shell to $newshell..."
     if [[ $RELEASE == 'Mac' ]]; then
         if ! finger "$USER" | grep -q "Shell.*$newshell"; then
             setshell=1
@@ -341,10 +348,10 @@ change_shell() {
             sudo chsh -s "$(which $newshell)" "$USER"
         fi
     fi
-    ok
 }
 
 full_config() {
+    echo
     echo "Do you want to set up personal configs? (git user/email, etc)"
     select choice in "Yes" "No"; do
         case $choice in
@@ -358,73 +365,11 @@ full_config() {
         esac
     done
 
-    echo -n "Setting up personal configurations..."
+    echo "Setting up personal configurations..."
     if ! git config --global --list | grep -q user.name; then
         git config --global user.name "Justin Dray"
         git config --global user.email "justin@dray.be"
     fi
-    ok
-}
-
-install_desktop_meta() {
-    [[ $RELEASE == "Mac" ]] && return
-    echo "Do you want to install desktop-only packages?"
-    select choice in "Yes" "No"; do
-        case $choice in
-        Yes)
-            break
-            ;;
-        No)
-            return
-            ;;
-        esac
-    done
-
-    case $RELEASE in
-    'Arch') install_command=install_desktop_arch ;;
-    *)
-        cat <<-EOF
-			You are not using a supported distro; package installation will be skipped. Make sure the required packages have been installed.
-			
-			Press enter to continue anyway, or ctrl+c to cancel
-		EOF
-        read -r
-        return
-        ;;
-    esac
-
-    $install_command
-}
-
-install_desktop_arch() {
-    if ! grep -qP "^\[multilib\]" /etc/pacman.conf; then
-        echo -n "Enabling multilib..."
-        echo '[multilib]' | sudo tee /etc/pacman >/dev/null
-        echo 'Include = /etc/pacman.d/mirrorlist' | sudo tee /etc/pacman >/dev/null
-        ok
-    fi
-
-    pyenv shell system &>/dev/null || :
-    echo "Installing desktop packages..."
-    create_package_list arch-desktop
-    yay -S --noconfirm --needed $PACINST
-
-    systemctl --user enable --now gamemoded syncthing
-    sudo systemctl enable --now docker bluetooth netdata
-    sudo usermod -a -G docker $USER
-
-    desktop_configure_background_changer
-}
-
-desktop_configure_background_changer() {
-    echo -n "Configuring background changer..."
-    if ! crontab -l | grep -q change-background; then
-        (
-            crontab -l 2>/dev/null || :
-            echo "*/2 * * * * $HOME/.scripts/change-background"
-        ) | crontab -
-    fi
-    ok
 }
 
 update_yadm
@@ -441,4 +386,3 @@ install_aws_cli
 configure_vim
 change_shell
 full_config
-install_desktop_meta
